FROM elixir:1.10.1-alpine as build

RUN apk add --update git build-base nodejs npm yarn python bash postgresql-client

ENV MIX_ENV=dev

RUN apk add --update git && \
    rm -rf /var/cache/apk/*

RUN mkdir /app
WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

COPY config ./config
COPY lib ./lib
COPY priv ./priv
COPY mix.exs .
COPY mix.lock .

EXPOSE 4001

RUN mix deps.get
RUN mix deps.compile
RUN mix phx.digest
RUN mix compile

COPY entrypoint.sh .
CMD ["bash", "/app/entrypoint.sh"]