version: "3"

networks:
  internal:
    external: false

services:
  prod:
    image: bank-api-prod
    build:
      context: .
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_DB=${DATABASE_DB}
      - DATABASE_HOST=db
    ports:
      - 4000:4000
    networks:
      - internal
    depends_on:
      - db

  dev:
    image: bank-api-dev
    build:
      context: .
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_DB=api_banking_dev
      - DATABASE_HOST_DEV=db
    ports:
      - 4001:4001
    networks:
      - internal
    depends_on:
      - db

  test:
    image: bank-api-test
    build:
      context: .
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_DB=api_banking_test
      - DATABASE_HOST_TEST=db
    ports:
      - 4002:4002
    networks:
      - internal
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${DATABASE_DB}
    networks:
      - internal
  db_event_source:
    image: postgres:12-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=${DATABASE_DB}
    networks:
      - internal
