apiVersion: v1
kind: Service
metadata:
  name: bank-api-node-port
spec:
  type: NodePort
  ports:
    - port: 4041
      targetPort: 4000
      nodePort: 32001
  selector:
    component: bank-api-web
